# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deliver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdeliver.proto\"\x1d\n\rSimpleRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\xb7\x02\n\x07\x42\x61rData\x12\r\n\x05Insid\x18\x01 \x01(\t\x12\x0f\n\x07Ts_open\x18\x02 \x01(\x03\x12\x12\n\nOpen_price\x18\x03 \x01(\x02\x12\x12\n\nHigh_price\x18\x04 \x01(\x02\x12\x11\n\tLow_price\x18\x05 \x01(\x02\x12\x13\n\x0b\x43lose_price\x18\x06 \x01(\x02\x12\x0b\n\x03Vol\x18\x07 \x01(\x02\x12\x0e\n\x06VolCcy\x18\x08 \x01(\x02\x12\x13\n\x0bVolCcyQuote\x18\t \x01(\x02\x12\n\n\x02Oi\x18\n \x01(\x02\x12\r\n\x05OiCcy\x18\x0b \x01(\x02\x12\r\n\x05Ts_oi\x18\x0c \x01(\x03\x12\x13\n\x0b\x46undingRate\x18\r \x01(\x02\x12\x17\n\x0fNextFundingRate\x18\x0e \x01(\x02\x12\x16\n\x0eTs_FundingRate\x18\x0f \x01(\x03\x12\x1a\n\x12TS_NextFundingRate\x18\x10 \x01(\x03\"}\n\x08TickData\x12\r\n\x05Insid\x18\x01 \x01(\t\x12\x10\n\x08Ts_Price\x18\x02 \x01(\x03\x12\x12\n\nAsk1_price\x18\x03 \x01(\x02\x12\x12\n\nBid1_price\x18\x04 \x01(\x02\x12\x13\n\x0b\x41sk1_volumn\x18\x05 \x01(\x02\x12\x13\n\x0b\x42id1_volumn\x18\x06 \x01(\x02\"\x1f\n\x08Response\x12\x13\n\x0bresponse_me\x18\x01 \x01(\t29\n\x0e\x42\x61rDataRevicer\x12\'\n\x0e\x42\x61rDataRevicer\x12\x08.BarData\x1a\t.Response\"\x00\x32<\n\x0fTickDataRevicer\x12)\n\x0fTickDataRevicer\x12\t.TickData\x1a\t.Response\"\x00\x42\x0bZ\t.;deliverb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deliver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\t.;deliver'
  _SIMPLEREQUEST._serialized_start=17
  _SIMPLEREQUEST._serialized_end=46
  _BARDATA._serialized_start=49
  _BARDATA._serialized_end=360
  _TICKDATA._serialized_start=362
  _TICKDATA._serialized_end=487
  _RESPONSE._serialized_start=489
  _RESPONSE._serialized_end=520
  _BARDATAREVICER._serialized_start=522
  _BARDATAREVICER._serialized_end=579
  _TICKDATAREVICER._serialized_start=581
  _TICKDATAREVICER._serialized_end=641
# @@protoc_insertion_point(module_scope)
