// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.0
// source: deliver.proto

package deliver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomDataReceiverClient is the client API for CustomDataReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomDataReceiverClient interface {
	CustomDataReceiver(ctx context.Context, in *BarData, opts ...grpc.CallOption) (*Response, error)
}

type customDataReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomDataReceiverClient(cc grpc.ClientConnInterface) CustomDataReceiverClient {
	return &customDataReceiverClient{cc}
}

func (c *customDataReceiverClient) CustomDataReceiver(ctx context.Context, in *BarData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/CustomDataReceiver/CustomDataReceiver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomDataReceiverServer is the server API for CustomDataReceiver service.
// All implementations must embed UnimplementedCustomDataReceiverServer
// for forward compatibility
type CustomDataReceiverServer interface {
	CustomDataReceiver(context.Context, *BarData) (*Response, error)
	mustEmbedUnimplementedCustomDataReceiverServer()
}

// UnimplementedCustomDataReceiverServer must be embedded to have forward compatible implementations.
type UnimplementedCustomDataReceiverServer struct {
}

func (UnimplementedCustomDataReceiverServer) CustomDataReceiver(context.Context, *BarData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CustomDataReceiver not implemented")
}
func (UnimplementedCustomDataReceiverServer) mustEmbedUnimplementedCustomDataReceiverServer() {}

// UnsafeCustomDataReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomDataReceiverServer will
// result in compilation errors.
type UnsafeCustomDataReceiverServer interface {
	mustEmbedUnimplementedCustomDataReceiverServer()
}

func RegisterCustomDataReceiverServer(s grpc.ServiceRegistrar, srv CustomDataReceiverServer) {
	s.RegisterService(&CustomDataReceiver_ServiceDesc, srv)
}

func _CustomDataReceiver_CustomDataReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BarData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomDataReceiverServer).CustomDataReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CustomDataReceiver/CustomDataReceiver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomDataReceiverServer).CustomDataReceiver(ctx, req.(*BarData))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomDataReceiver_ServiceDesc is the grpc.ServiceDesc for CustomDataReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomDataReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CustomDataReceiver",
	HandlerType: (*CustomDataReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CustomDataReceiver",
			Handler:    _CustomDataReceiver_CustomDataReceiver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deliver.proto",
}

// SubmitServerReceiverClient is the client API for SubmitServerReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubmitServerReceiverClient interface {
	SubmitServerReceiver(ctx context.Context, in *LocalSubmit, opts ...grpc.CallOption) (*Response, error)
}

type submitServerReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewSubmitServerReceiverClient(cc grpc.ClientConnInterface) SubmitServerReceiverClient {
	return &submitServerReceiverClient{cc}
}

func (c *submitServerReceiverClient) SubmitServerReceiver(ctx context.Context, in *LocalSubmit, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/SubmitServerReceiver/SubmitServerReceiver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubmitServerReceiverServer is the server API for SubmitServerReceiver service.
// All implementations must embed UnimplementedSubmitServerReceiverServer
// for forward compatibility
type SubmitServerReceiverServer interface {
	SubmitServerReceiver(context.Context, *LocalSubmit) (*Response, error)
	mustEmbedUnimplementedSubmitServerReceiverServer()
}

// UnimplementedSubmitServerReceiverServer must be embedded to have forward compatible implementations.
type UnimplementedSubmitServerReceiverServer struct {
}

func (UnimplementedSubmitServerReceiverServer) SubmitServerReceiver(context.Context, *LocalSubmit) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitServerReceiver not implemented")
}
func (UnimplementedSubmitServerReceiverServer) mustEmbedUnimplementedSubmitServerReceiverServer() {}

// UnsafeSubmitServerReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubmitServerReceiverServer will
// result in compilation errors.
type UnsafeSubmitServerReceiverServer interface {
	mustEmbedUnimplementedSubmitServerReceiverServer()
}

func RegisterSubmitServerReceiverServer(s grpc.ServiceRegistrar, srv SubmitServerReceiverServer) {
	s.RegisterService(&SubmitServerReceiver_ServiceDesc, srv)
}

func _SubmitServerReceiver_SubmitServerReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalSubmit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubmitServerReceiverServer).SubmitServerReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SubmitServerReceiver/SubmitServerReceiver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubmitServerReceiverServer).SubmitServerReceiver(ctx, req.(*LocalSubmit))
	}
	return interceptor(ctx, in, info, handler)
}

// SubmitServerReceiver_ServiceDesc is the grpc.ServiceDesc for SubmitServerReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubmitServerReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SubmitServerReceiver",
	HandlerType: (*SubmitServerReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitServerReceiver",
			Handler:    _SubmitServerReceiver_SubmitServerReceiver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deliver.proto",
}

// TickDataReceiverClient is the client API for TickDataReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickDataReceiverClient interface {
	TickDataReceiver(ctx context.Context, in *TickData, opts ...grpc.CallOption) (*Response, error)
}

type tickDataReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewTickDataReceiverClient(cc grpc.ClientConnInterface) TickDataReceiverClient {
	return &tickDataReceiverClient{cc}
}

func (c *tickDataReceiverClient) TickDataReceiver(ctx context.Context, in *TickData, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/TickDataReceiver/TickDataReceiver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TickDataReceiverServer is the server API for TickDataReceiver service.
// All implementations must embed UnimplementedTickDataReceiverServer
// for forward compatibility
type TickDataReceiverServer interface {
	TickDataReceiver(context.Context, *TickData) (*Response, error)
	mustEmbedUnimplementedTickDataReceiverServer()
}

// UnimplementedTickDataReceiverServer must be embedded to have forward compatible implementations.
type UnimplementedTickDataReceiverServer struct {
}

func (UnimplementedTickDataReceiverServer) TickDataReceiver(context.Context, *TickData) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TickDataReceiver not implemented")
}
func (UnimplementedTickDataReceiverServer) mustEmbedUnimplementedTickDataReceiverServer() {}

// UnsafeTickDataReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickDataReceiverServer will
// result in compilation errors.
type UnsafeTickDataReceiverServer interface {
	mustEmbedUnimplementedTickDataReceiverServer()
}

func RegisterTickDataReceiverServer(s grpc.ServiceRegistrar, srv TickDataReceiverServer) {
	s.RegisterService(&TickDataReceiver_ServiceDesc, srv)
}

func _TickDataReceiver_TickDataReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TickData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TickDataReceiverServer).TickDataReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TickDataReceiver/TickDataReceiver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TickDataReceiverServer).TickDataReceiver(ctx, req.(*TickData))
	}
	return interceptor(ctx, in, info, handler)
}

// TickDataReceiver_ServiceDesc is the grpc.ServiceDesc for TickDataReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TickDataReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TickDataReceiver",
	HandlerType: (*TickDataReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TickDataReceiver",
			Handler:    _TickDataReceiver_TickDataReceiver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deliver.proto",
}

// OrerReceiverClient is the client API for OrerReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrerReceiverClient interface {
	OrerRReceiver(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Response, error)
}

type orerReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewOrerReceiverClient(cc grpc.ClientConnInterface) OrerReceiverClient {
	return &orerReceiverClient{cc}
}

func (c *orerReceiverClient) OrerRReceiver(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/OrerReceiver/OrerRReceiver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrerReceiverServer is the server API for OrerReceiver service.
// All implementations must embed UnimplementedOrerReceiverServer
// for forward compatibility
type OrerReceiverServer interface {
	OrerRReceiver(context.Context, *Order) (*Response, error)
	mustEmbedUnimplementedOrerReceiverServer()
}

// UnimplementedOrerReceiverServer must be embedded to have forward compatible implementations.
type UnimplementedOrerReceiverServer struct {
}

func (UnimplementedOrerReceiverServer) OrerRReceiver(context.Context, *Order) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrerRReceiver not implemented")
}
func (UnimplementedOrerReceiverServer) mustEmbedUnimplementedOrerReceiverServer() {}

// UnsafeOrerReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrerReceiverServer will
// result in compilation errors.
type UnsafeOrerReceiverServer interface {
	mustEmbedUnimplementedOrerReceiverServer()
}

func RegisterOrerReceiverServer(s grpc.ServiceRegistrar, srv OrerReceiverServer) {
	s.RegisterService(&OrerReceiver_ServiceDesc, srv)
}

func _OrerReceiver_OrerRReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrerReceiverServer).OrerRReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OrerReceiver/OrerRReceiver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrerReceiverServer).OrerRReceiver(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

// OrerReceiver_ServiceDesc is the grpc.ServiceDesc for OrerReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrerReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "OrerReceiver",
	HandlerType: (*OrerReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OrerRReceiver",
			Handler:    _OrerReceiver_OrerRReceiver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deliver.proto",
}

// JsonReceiverClient is the client API for JsonReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JsonReceiverClient interface {
	JsonReceiver(ctx context.Context, in *JsonInfo, opts ...grpc.CallOption) (*Response, error)
}

type jsonReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewJsonReceiverClient(cc grpc.ClientConnInterface) JsonReceiverClient {
	return &jsonReceiverClient{cc}
}

func (c *jsonReceiverClient) JsonReceiver(ctx context.Context, in *JsonInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/JsonReceiver/JsonReceiver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JsonReceiverServer is the server API for JsonReceiver service.
// All implementations must embed UnimplementedJsonReceiverServer
// for forward compatibility
type JsonReceiverServer interface {
	JsonReceiver(context.Context, *JsonInfo) (*Response, error)
	mustEmbedUnimplementedJsonReceiverServer()
}

// UnimplementedJsonReceiverServer must be embedded to have forward compatible implementations.
type UnimplementedJsonReceiverServer struct {
}

func (UnimplementedJsonReceiverServer) JsonReceiver(context.Context, *JsonInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JsonReceiver not implemented")
}
func (UnimplementedJsonReceiverServer) mustEmbedUnimplementedJsonReceiverServer() {}

// UnsafeJsonReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JsonReceiverServer will
// result in compilation errors.
type UnsafeJsonReceiverServer interface {
	mustEmbedUnimplementedJsonReceiverServer()
}

func RegisterJsonReceiverServer(s grpc.ServiceRegistrar, srv JsonReceiverServer) {
	s.RegisterService(&JsonReceiver_ServiceDesc, srv)
}

func _JsonReceiver_JsonReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JsonInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonReceiverServer).JsonReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/JsonReceiver/JsonReceiver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonReceiverServer).JsonReceiver(ctx, req.(*JsonInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// JsonReceiver_ServiceDesc is the grpc.ServiceDesc for JsonReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JsonReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "JsonReceiver",
	HandlerType: (*JsonReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JsonReceiver",
			Handler:    _JsonReceiver_JsonReceiver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "deliver.proto",
}
